---
spring:
  config:
    import: classpath:application-common.yml
---

spring:
  application:
    name: spring-ai-mcp-server
  ai:
    mcp:
      server:
        name: ${spring.application.name}

server:
  port: 8989

my:
  kong:
    base-url: ${my_kong_base_url:http://127.0.0.1:8001}

management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true
  observations:
    annotations:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ${management_endpoints_web_exposure_include:health,prometheus}