version: '3.8'
services:
  spring-ai-mcp-server:
    build:
      dockerfile: Dockerfile
      context: .
      additional_contexts:
        parent: ../
    image: spring-ai-mcp-server:latest
    container_name: spring-ai-mcp-server
    ports:
      #      - "8989:8989"
      - "18989:18989"
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:18989
      my_kong_base_url: http://kong-gateway:8001
    restart: always
    networks:
      - mcp
networks:
  mcp:
    external: true