spring:
  config:
    import: classpath:application-common.yml
---
spring:
  application:
    name: spring-ai-mcp-client
  ai:
    memory:
      redis:
        host: ${spring_ai_memory_redis_host:127.0.0.1}
    mcp:
      client:
        enabled: true
        name: ${spring.application.name}
        initialized: true
        type: async
        toolcallback:
          enabled: true
        streamable-http:
          connections:
            mcp-server:
              url: ${spring_ai_mcp_client_streamable_http_connections_mcp_server_url:http://localhost:8000/mcp-server/demo}
              endpoint: ${spring_ai_mcp_client_streamable_http_connections_mcp_server_endpoint:/streamable-http}
    openai:
      api-key: ${spring_ai_openai_api_key:noUse}
      base-url: ${spring_ai_openai_base_url:https://api.openai.com}
      chat:
        completions-path: ${spring_ai_openai_chat_completions_path:/v1/chat/completions}
        options:
          model: ${spring_ai_openai_chat_options_model:gpt-4o}
server:
  port: 8987