version: '3.8'
services:
  spring-ai-mcp-client:
    build:
      dockerfile: Dockerfile
      context: .
      additional_contexts:
        parent: ../
    image: spring-ai-mcp-client:latest
    container_name: spring-ai-mcp-client
    ports:
      #      - "8987:8987"
      - "18987:18987"
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:18987
      spring_ai_memory_redis_host: redis
      spring_ai_openai_base_url: http://kong-gateway:8000
      spring_ai_openai_chat_completions_path: /llm/openai-chat
      spring_ai_openai_chat_options_model: gpt-4o
      spring_ai_mcp_client_sse_connections_example_url: http://kong-gateway:8000/mcp-server/demo
    restart: always
    networks:
      - mcp
networks:
  mcp:
    external: true