---
spring:
  config:
    import: classpath:application-common.yml
---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/mcp
  application:
    name: spring-ai-mcp-server-account-security
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        protocol: streamable
        type: sync
        enabled: true
        stdio: false
        annotation-scanner:
          enabled: true
        capabilities:
          tool: true
        streamable-http:
          mcp-endpoint: /mcp
        tool-change-notification: true
  datasource:
    url: jdbc:h2:mem:test-security
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    database: h2
    open-in-view: false
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
server:
  servlet:
    session:
      cookie:
        name: MCP_SERVER_STREAMABLE_HTTP_SECURED_TOOLS_SESSIONID
  port: 8989