spring:
  config:
    import: classpath:application-common.yml
---
spring:
  security:
    oauth2:
      client:
        registration:
          auth-code:
            provider: authserver
            authorization-grant-type: authorization_code
            client-secret: OAsvrq0eNk07uGnCmlqRdGkfysNwrwTX
            client-id: mcp-client
          client-credentials:
            provider: authserver
            authorization-grant-type: client_credentials
            client-secret: OAsvrq0eNk07uGnCmlqRdGkfysNwrwTX
            client-id: mcp-client
        provider:
          authserver:
            issuer-uri: http://localhost:8080/realms/mcp
  application:
    name: spring-ai-mcp-client
  ai:
    memory:
      redis:
        host: ${spring_ai_memory_redis_host:127.0.0.1}
    mcp:
      client:
        name: ${spring.application.name}
        enabled: true
        toolcallback:
          enabled: true
        initialized: false
        type: sync
        streamable-http:
          connections:
            mcp-server:
              url: ${spring_ai_mcp_client_streamable_http_connections_mcp_server_url:http://localhost:8989}
              endpoint: ${spring_ai_mcp_client_streamable_http_connections_mcp_server_endpoint:/mcp}
        annotation-scanner:
          enabled: true
    openai:
      api-key: ${spring_ai_openai_api_key:nothing}
      base-url: ${spring_ai_openai_base_url:https://api.openai.com}
      chat:
        completions-path: ${spring_ai_openai_chat_completions_path:/v1/chat/completions}
        options:
          model: ${spring_ai_openai_chat_options_model:gpt-4o-mini}
server:
  port: 8987